version: "3.8"

services:
  zeroshot-classifier:
    container_name: zeroshot-classifier
    image: heartexlabs/label-studio-ml-backend:zeroshot-classifier
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    environment:
      - BASELINE_MODEL_NAME=MoritzLaurer/bge-m3-zeroshot-v2.0
      - LOG_LEVEL=DEBUG
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      - "./data/.cache:/root/.cache"
